// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/chochanghun/Desktop/ReactNativeTheBook/PublicGallerycvcvcx/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/chochanghun/Desktop/ReactNativeTheBook/PublicGallerycvcvcx/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('PublicGallerycvcvcx', appParameters);
});
require('/Users/chochanghun/Desktop/ReactNativeTheBook/PublicGallerycvcvcx/index.js');